---
name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and test Java ${{ matrix.java }}
    permissions:
      checks: write
      pull-requests: write
    env:
      MAIN_JAVA_VER: 17
    strategy:
      matrix:
        java: [17, 20]
  steps:
  - name: Checkout sources
    uses: actions/checkout@v3

  - name: Setup Java ${{ matrix.java }}
    uses: actions/setup-java@v3
    with:
      distribution: temurin
      java-version: ${{ matrix.java }}
      cache: maven

  - name: Verify the project and create coverage report
    run: mvn verify -Pits,cov -B -ff

  - name: Report test summary
    if: ${{ matrix.java == env.MAIN_JAVA_VER  && always() }}
    uses: EnricoMi/publish-unit-test-result-action@v2
    with:
      test_changes_limit: 0
      files: ./target/junit-platform/TEST-junit-jupiter.xml

  - name: Upload coverage reports
    if: ${{ matrix.java == env.MAIN_JAVA_VER }}
    uses: actions/upload-artifact@v3
    with:
      name: coverage
      path: ./target/site/jacoco/jacoco.xml
