---
name: Stage

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "**.md"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy snapshot
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Get pom specs
        id: project
        run: |
          echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_OUTPUT"

      - name: Deploy snapshot to GitHub
        if: contains(steps.project.outputs.version, 'SNAPSHOT')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn deploy -Pprepare-deployment,deploy-github -B -ff
